import { type RouteRiskScoringConfig, riskScoringForRoute } from './routeRiskScoring';

export type { FieldRiskScoreConfig, RouteRiskScoringConfig } from './routeRiskScoring';

export type RouteKey =
  | 'uk_to_dubai'
  | 'professionals_to_uk'
  | 'students_to_uk'
  | 'families_to_uk'
  | 'leaving_uk';

export type PackageKey =
  | 'tax_residence_packet'
  | 'banking_readiness'
  | 'documents_attestation_pack'
  | 'housing_ejari_readiness'
  | 'housing_readiness'
  | 'healthcare_insurance_setup'
  | 'healthcare_setup'
  | 'family_arrival_pack'
  | 'credentials_licences_conversion'
  | 'pet_relocation_readiness'
  | 'storage_shipping_plan'
  | 'estate_wills_packet'
  | 'first_90_days_concierge'
  | 'day_one_arrival_pack'
  | 'school_nursery_setup'
  | 'student_arrival_pack'
  | 'student_document_readiness'
  | 'parent_emergency_pack'
  | 'safety_scams_pack'
  | 'documents_family_records_pack'
  | 'uk_departure_admin_pack'
  | 'banking_continuity'
  | 'property_pension_investments_packet';

export type RouteConfig = {
  routeKey: RouteKey;
  slug: string;
  title: string;
  heroHeadline: string;
  heroSubhead: string;
  painPoints: string[];
  checks: string[];
  livingPriceGbp: number;
  checkFields: string[];
  livingReportFields: string[];
  reportSections: string[];
  packages: PackageKey[];
  riskScoring: RouteRiskScoringConfig;
};

const ROUTE_CONFIG_BASE = [
  {
    routeKey: 'uk_to_dubai',
    slug: 'uk-to-dubai',
    title: 'UK to Dubai',
    heroHeadline: 'Moving from the UK to Dubai?',
    heroSubhead:
      'Start with a free Lifeport Check on the hidden dependencies behind your move — then unlock a Lifeport Plan for tax timing, UAE setup, documents, banking, housing, family logistics, pets, storage and your first 90 days.',
    painPoints: [
      'Your UK departure date, UK ties and return visits can affect your Statutory Residence Test and split-year position.',
      'A UAE resident setup often depends on a sequence: entry/residence process, medical fitness, Emirates ID, health insurance, banking, tenancy and utilities.',
      'Dubai banking is rarely just “open an app”: salary letters, Emirates ID, UAE address, source-of-funds checks and fallback money access matter.',
      'Housing, Ejari, DEWA/utilities and proof-of-address can become a circular dependency for banking, family sponsorship and school setup.',
      'UK property, pensions, ISAs, investments, company equity and rental income can continue to create UK admin after departure.',
      'Documents often need planning before you leave: degree certificates, marriage/birth certificates, school records, translations, apostilles or UAE attestation.',
      'Driving licence exchange, pet import, shipping, temporary storage and healthcare cover are often discovered too late.',
      'If moving with family, school admissions, health insurance, dependant documents and guardianship/wills need their own timeline.',
    ],
    checks: [
      'UK tax residence and split-year readiness',
      'UK departure admin: HMRC, P85/SA109, self-assessment, council, mail and records',
      'UAE residence setup: visa route, medical fitness, Emirates ID and health insurance',
      'Dubai banking readiness and first-month money plan',
      'Housing, Ejari, utilities and proof-of-address dependencies',
      'UK property, rental income, mortgages, pensions, ISAs and investments',
      'Document attestation: degree, marriage, birth, school and professional records',
      'Driving licence exchange and car/insurance setup',
      'Healthcare, prescriptions and insurance during the transition',
      'Family, school, nursery, spouse/dependant and emergency setup',
      'Pet relocation requirements and animal travel timing',
      'Shipping, storage, valuables and first-30-days essentials',
      'Estate, wills, guardianship and cross-border asset prompts',
      'First week, first month and first 90 days in Dubai',
    ],
    livingPriceGbp: 499,
    checkFields: [
      'email',
      'name',
      'originCountry',
      'destinationCountry',
      'destinationCity',
      'citizenships',
      'moveDate',
      'moveDateFlexibility',
      'moveReason',
      'householdType',
      'hasChildren',
      'hasPets',
      'employmentStatus',
      'visaStatus',
      'housingStatus',
      'bankingStatus',
      'ownsUkProperty',
      'hasUkPensionIsaInvestments',
      'topConcerns',
      'biggestWorry',
    ],
    livingReportFields: [
      'currentUkTaxResidenceStatus',
      'taxResidenceLastFiveYears',
      'expectedUkDaysAfterMove',
      'ukTiesHomeWorkFamily',
      'ukEmploymentOrBusinessAfterMove',
      'uaeVisaRoute',
      'employerSponsorStatus',
      'emiratesIdStatus',
      'healthInsuranceStatusUae',
      'uaeHousingPlan',
      'ejariStatus',
      'dewaUtilitiesStatus',
      'bankingNeedsSalaryRentFamilyTransfers',
      'currentBankAccounts',
      'sourceOfFundsComplexity',
      'assetsPropertyPension',
      'ukPropertyRentalOrSalePlans',
      'isaSippPensionDetails',
      'companyEquityOrCrypto',
      'dependants',
      'childrenAges',
      'schoolOrNurseryNeeds',
      'spouseWorkPlans',
      'petsDetails',
      'petVaccinationMicrochipStatus',
      'drivingLicenceCountry',
      'needsUaeDrivingLicence',
      'documentsNeedingAttestation',
      'degreeProfessionalQualifications',
      'marriageBirthSchoolRecords',
      'shippingStorageNeeds',
      'temporaryAccommodationNeeds',
      'healthConditionsPrescriptions',
      'existingWillsEstatePlans',
      'expertAdvisersAlreadyEngaged',
    ],
    reportSections: [
      'executive_brief',
      'move_profile',
      'hidden_dependencies',
      'risk_map',
      'timeline',
      'uk_departure_admin',
      'tax_residence',
      'uae_residency_emirates_id',
      'banking_money',
      'housing_ejari_utilities',
      'healthcare_insurance',
      'family_school_dependants',
      'pets_animal_travel',
      'credentials_licences_attestation',
      'shipping_storage_possessions',
      'property_pension_investments',
      'estate_wills_guardianship',
      'day_one_arrival',
      'first_90_days',
      'recommended_packages',
      'expert_questions',
      'change_log',
    ],
    packages: [
      'day_one_arrival_pack',
      'tax_residence_packet',
      'banking_readiness',
      'documents_attestation_pack',
      'housing_ejari_readiness',
      'healthcare_insurance_setup',
      'family_arrival_pack',
      'credentials_licences_conversion',
      'pet_relocation_readiness',
      'storage_shipping_plan',
      'estate_wills_packet',
      'first_90_days_concierge',
    ],
  },
  {
    routeKey: 'professionals_to_uk',
    slug: 'professionals-to-uk',
    title: 'Professionals to UK',
    heroHeadline: 'Your company moves your job. Lifeport helps move your life.',
    heroSubhead:
      'Get a free Lifeport Check on the parts your employer may not handle — then unlock a Lifeport Plan for UK arrival, eVisa, banking, housing, healthcare, tax, family, credentials and your first 90 days.',
    painPoints: [
      'Your employer may handle the visa sponsorship but not your banking, housing, GP, family, school, driving licence or proof-of-address setup.',
      'The UK immigration-status workflow is now digital-first: UKVI account, eVisa and share codes for right to work and right to rent.',
      'A UK bank account can depend on identity, immigration status, UK address, employer documents and sometimes a phone number.',
      'Right to rent, tenancy, deposit, utilities and proof-of-address can become circular dependencies.',
      'National Insurance number, payroll, tax code and first salary setup are easy to forget until onboarding starts.',
      'If moving with a partner or children, dependant visas, school timing, nursery waitlists and healthcare records create a separate family critical path.',
      'Foreign driving licences, professional qualifications, degree comparability and regulated profession requirements may need review.',
      'Shipping, storage, pets and temporary accommodation can become blockers if permanent housing is not ready.',
    ],
    checks: [
      'Work visa, dependant visa and employer support gaps',
      'eVisa, UKVI account, right-to-work and right-to-rent share codes',
      'National Insurance number, payroll and tax-code readiness',
      'UK banking, proof-of-address and first-month money plan',
      'Housing, tenancy, deposit, guarantor and utilities readiness',
      'NHS/IHS, GP registration, prescriptions and private insurance prompts',
      'Spouse, children, schools, nursery and family arrival setup',
      'Driving licence exchange or 12-month foreign-licence planning',
      'Degree, diploma and professional qualification recognition',
      'Pets, shipping, storage and temporary accommodation',
      'UK tax-residence arrival year and foreign income/assets flags',
      'Estate, wills, beneficiaries and guardianship prompts',
      'First week, first month and first 90 days in the UK',
    ],
    livingPriceGbp: 299,
    checkFields: [
      'email',
      'name',
      'originCountry',
      'destinationCountry',
      'destinationCity',
      'citizenships',
      'moveDate',
      'workStartDate',
      'householdType',
      'hasChildren',
      'hasPets',
      'employmentStatus',
      'visaStatus',
      'employerSupportLevel',
      'housingStatus',
      'bankingStatus',
      'previousUkResidence',
      'topConcerns',
      'biggestWorry',
    ],
    livingReportFields: [
      'visaRoute',
      'certificateOfSponsorshipStatus',
      'ukviAccountStatus',
      'evisaStatus',
      'rightToWorkReadiness',
      'rightToRentReadiness',
      'dependants',
      'dependantVisaStatus',
      'salaryBand',
      'payrollStartDate',
      'nationalInsuranceNumberStatus',
      'taxCodeKnown',
      'foreignIncomeOrAssets',
      'propertyAbroad',
      'currentBankingSetup',
      'ukProofOfAddressPlan',
      'ukPhoneNumberPlan',
      'housingBudget',
      'temporaryAccommodationNeeds',
      'childrenAges',
      'schoolOrNurseryNeeds',
      'healthConditionsPrescriptions',
      'privateMedicalInsuranceStatus',
      'drivingLicenceCountry',
      'needsCarInUk',
      'professionalQualifications',
      'degreeDocuments',
      'regulatedProfession',
      'petsDetails',
      'shippingStorageNeeds',
      'documentsTranslationsApostille',
      'estateWillsGuardianshipStatus',
    ],
    reportSections: [
      'executive_brief',
      'move_profile',
      'hidden_dependencies',
      'risk_map',
      'timeline',
      'visa_admin_evisa_share_codes',
      'work_payroll_ni_tax_code',
      'banking_money',
      'housing_right_to_rent_utilities',
      'healthcare_gp_nhs_insurance',
      'family_school_dependants',
      'pets_animal_travel',
      'credentials_licences_conversion',
      'shipping_storage_possessions',
      'tax_residence',
      'estate_wills_guardianship',
      'day_one_arrival',
      'first_90_days',
      'recommended_packages',
      'expert_questions',
      'change_log',
    ],
    packages: [
      'day_one_arrival_pack',
      'banking_readiness',
      'housing_readiness',
      'healthcare_setup',
      'credentials_licences_conversion',
      'family_arrival_pack',
      'school_nursery_setup',
      'pet_relocation_readiness',
      'storage_shipping_plan',
      'tax_residence_packet',
      'first_90_days_concierge',
    ],
  },
  {
    routeKey: 'students_to_uk',
    slug: 'students-to-uk',
    title: 'Students to UK',
    heroHeadline: 'Starting university in the UK?',
    heroSubhead:
      'Get a free Lifeport Check for your UK arrival — then unlock a Lifeport Plan for CAS, visa, eVisa, accommodation, banking, healthcare, safety, parent funding and your first term.',
    painPoints: [
      'After the offer and CAS, students still need to coordinate visa status, eVisa access, travel, accommodation, banking, GP registration and university enrolment.',
      'UK bank account setup can depend on passport, student visa, proof of address and a university bank letter or student-status letter.',
      'Parents often need a safe funding plan for tuition, rent, living money, FX, emergency cards and fraud/scam avoidance.',
      'Accommodation creates knock-on effects: proof of address, bank letters, deliveries, GP catchment and arrival-week logistics.',
      'Most Student-route dependants are now restricted, so family plans need early checking if a partner or child is involved.',
      'Outdated advice still circulates around BRPs and police registration; the current friction is usually eVisa/UKVI account and share-code readiness.',
      'First-week tasks can pile up: university registration, student ID, phone/SIM, bank, GP, transport, groceries, safety and emergency contacts.',
      'Under-18 students, health conditions, prescriptions, disability support or guardianship needs require a separate support plan.',
    ],
    checks: [
      'CAS, Student visa, IHS and eVisa readiness',
      'UKVI account and immigration-status proof',
      'University registration, student ID and bank-letter timing',
      'Accommodation, tenancy, guarantor, deposit and move-in readiness',
      'Student bank account documents and first-month money plan',
      'Parent funding, FX transfers, tuition/rent payment safety and emergency access',
      'Phone/SIM, transport, groceries and arrival-week basics',
      'GP registration, healthcare, prescriptions and wellbeing support',
      'Safety, scams, emergency contacts and parent communication',
      'Student dependant eligibility if partner/children are involved',
      'Documents, translations, transcripts and student-record readiness',
      'First week, first month and first term in the UK',
    ],
    livingPriceGbp: 99,
    checkFields: [
      'email',
      'name',
      'originCountry',
      'destinationCountry',
      'destinationCity',
      'citizenships',
      'moveDate',
      'studentAge',
      'university',
      'courseLevel',
      'courseStartDate',
      'casStatus',
      'visaStatus',
      'accommodationStatus',
      'bankingStatus',
      'parentInvolved',
      'arrivingAlone',
      'topConcerns',
      'biggestWorry',
    ],
    livingReportFields: [
      'university',
      'campusCity',
      'courseName',
      'courseLevel',
      'courseStartDate',
      'casIssuedDate',
      'studentVisaApplicationStatus',
      'visaDecisionStatus',
      'ihsPaymentStatus',
      'ukviAccountStatus',
      'evisaStatus',
      'passportExpiryDate',
      'arrivalDateTime',
      'airportArrivalPlan',
      'accommodationType',
      'tenancyOrHallsContractStatus',
      'guarantorOrDepositNeeds',
      'proofOfAddressPlan',
      'studentBankLetterAvailability',
      'currentBankingSetup',
      'tuitionPaymentStatus',
      'rentPaymentPlan',
      'parentFundingPlan',
      'fxTransferNeeds',
      'ukPhoneSimPlan',
      'gpRegistrationPlan',
      'healthConditionsPrescriptions',
      'disabilityOrWellbeingSupportNeeds',
      'vaccinationRecords',
      'emergencyContacts',
      'familyVisitorsPlan',
      'dependants',
      'under18GuardianNeeds',
      'documentsTranslations',
      'degreeDiplomaTranscripts',
      'scholarshipIncome',
      'partTimeWorkIntent',
      'safetyScamConcerns',
    ],
    reportSections: [
      'executive_brief',
      'move_profile',
      'hidden_dependencies',
      'risk_map',
      'timeline',
      'student_visa_cas_evisa',
      'university_registration',
      'banking_money_parent_funding',
      'accommodation_housing',
      'healthcare_gp_wellbeing',
      'student_safety_scams',
      'family_parent_communication',
      'documents_credentials',
      'day_one_arrival',
      'first_week_first_term',
      'recommended_packages',
      'expert_questions',
      'change_log',
    ],
    packages: [
      'day_one_arrival_pack',
      'student_arrival_pack',
      'student_document_readiness',
      'banking_readiness',
      'housing_readiness',
      'healthcare_setup',
      'parent_emergency_pack',
      'safety_scams_pack',
      'first_90_days_concierge',
    ],
  },
  {
    routeKey: 'families_to_uk',
    slug: 'families-to-uk',
    title: 'Families to UK',
    heroHeadline: 'Moving your family to the UK?',
    heroSubhead:
      'Get a free Lifeport Check on the critical path across visas, housing, school, healthcare, money, pets, documents and arrival — then unlock the Lifeport Plan for the full family plan.',
    painPoints: [
      'Family relocation is not one move: the main applicant, partner, children, pets, documents and housing all have different dependencies.',
      'Dependant visa timing can be tied to the main applicant’s route, expiry date and eligibility conditions.',
      'School admissions depend on age, arrival date, local authority process, right to reside and often the housing area or catchment.',
      'Nursery and childcare can require early planning before permanent housing is finalised.',
      'Right to rent, proof of address, tenancy deposits, utilities and banking often form a circular dependency.',
      'GP registration is simple in principle, but families still need prescription, vaccination, dental, health-record and special-needs planning.',
      'Marriage certificates, birth certificates, custody/consent documents, translations and school records often need collecting before departure.',
      'Pets, shipping, temporary storage and first-month essentials can create expensive last-minute problems.',
      'Wills, guardianship and emergency contacts matter more when children or dependants are moving.',
    ],
    checks: [
      'Main applicant route and dependant visa readiness',
      'eVisa, UKVI account, right-to-work and right-to-rent share codes',
      'Housing, tenancy, deposits, guarantor and utilities dependencies',
      'School admissions, year-group mapping and nursery/childcare planning',
      'NHS/IHS, GP registration, vaccinations, prescriptions and family health records',
      'Family banking, proof of address and first-month money setup',
      'Marriage, birth, school, custody and translated document readiness',
      'Driving licence, car insurance and transport needs',
      'Pets, animal travel and pet-friendly housing',
      'Shipping, storage and first-30-days essentials',
      'Estate, wills, guardianship and emergency contacts',
      'First week, first month and first 90 days as a family in the UK',
    ],
    livingPriceGbp: 399,
    checkFields: [
      'email',
      'name',
      'originCountry',
      'destinationCountry',
      'destinationCity',
      'citizenships',
      'moveDate',
      'householdType',
      'primaryApplicantVisaStatus',
      'partnerMoving',
      'hasChildren',
      'childrenAges',
      'hasPets',
      'housingStatus',
      'schoolNeeds',
      'bankingStatus',
      'healthcareConcerns',
      'topConcerns',
      'biggestWorry',
    ],
    livingReportFields: [
      'primaryApplicantVisaRoute',
      'primaryApplicantWorkOrStudyStartDate',
      'dependants',
      'dependantVisaStatus',
      'partnerWorkPlans',
      'childrenAges',
      'childrenCurrentSchoolYears',
      'schoolPreferences',
      'localAuthorityAreaIfKnown',
      'nurseryChildcareNeeds',
      'specialEducationNeeds',
      'custodyConsentDocuments',
      'birthMarriageCertificates',
      'documentsTranslationsApostille',
      'housingBudget',
      'temporaryAccommodationNeeds',
      'rightToRentReadiness',
      'ukProofOfAddressPlan',
      'familyBankingNeeds',
      'currentBankingSetup',
      'healthConditionsPrescriptions',
      'vaccinationRecords',
      'dentalOpticalNeeds',
      'privateMedicalInsuranceStatus',
      'drivingLicenceCountry',
      'needsCarInUk',
      'petsDetails',
      'petVaccinationMicrochipStatus',
      'shippingStorageNeeds',
      'emergencyContacts',
      'estateWillsGuardianshipStatus',
      'previousUkResidence',
      'foreignIncomeOrAssets',
    ],
    reportSections: [
      'executive_brief',
      'move_profile',
      'hidden_dependencies',
      'risk_map',
      'timeline',
      'visa_admin_evisa_share_codes',
      'housing_right_to_rent_utilities',
      'family_school_nursery_dependants',
      'healthcare_gp_nhs_insurance',
      'banking_money',
      'documents_family_records',
      'pets_animal_travel',
      'credentials_licences_conversion',
      'shipping_storage_possessions',
      'tax_residence',
      'estate_wills_guardianship',
      'day_one_arrival',
      'first_90_days',
      'recommended_packages',
      'expert_questions',
      'change_log',
    ],
    packages: [
      'day_one_arrival_pack',
      'family_arrival_pack',
      'school_nursery_setup',
      'housing_readiness',
      'banking_readiness',
      'healthcare_setup',
      'documents_family_records_pack',
      'pet_relocation_readiness',
      'storage_shipping_plan',
      'estate_wills_packet',
      'first_90_days_concierge',
    ],
  },
  {
    routeKey: 'leaving_uk',
    slug: 'leaving-uk',
    title: 'Leaving the UK',
    heroHeadline: 'Leaving the UK?',
    heroSubhead:
      'Get a free Lifeport Check on what may follow you across the border — then unlock a Lifeport Plan for tax residence, HMRC, banking, property, pensions, documents, family, pets, storage and your first 90 days abroad.',
    painPoints: [
      'Leaving the UK does not automatically make you non-UK resident: the Statutory Residence Test, split-year rules, day counts and UK ties matter.',
      'HMRC departure admin can involve P85, SA109, Self Assessment, PAYE, National Insurance, student loans, benefits and address updates.',
      'UK property creates ongoing questions: sell, rent, mortgage consent, landlord registration, insurance, non-resident landlord scheme and CGT reporting.',
      'ISAs, SIPPs, workplace pensions, state pension, investment accounts and broker restrictions can change once you are non-UK resident.',
      'UK bank accounts, credit cards, phone numbers, two-factor authentication and proof-of-address dependencies can break after departure.',
      'Destination setup often depends on documents you should collect before leaving: birth, marriage, degree, police, school, health and pet records.',
      'Shipping, temporary storage, mail forwarding, valuables, first-month essentials and pet travel need their own timeline.',
      'Estate planning, wills, beneficiaries, guardianship and inheritance-tax exposure may need review if assets or family span countries.',
    ],
    checks: [
      'UK tax residence, SRT, split-year and expected UK day counts',
      'HMRC departure admin: P85, SA109, Self Assessment, PAYE and address updates',
      'UK property: sale, rental, mortgage, insurance, CGT and non-resident landlord prompts',
      'Pensions, ISAs, investments, brokers, state pension and National Insurance',
      'UK banking continuity, cards, phone numbers, 2FA and overseas address risk',
      'Destination visa/residence, healthcare, banking and housing dependencies',
      'Document legalisation, apostille, translation and credential conversion needs',
      'Driving licence conversion and no-claims/insurance records',
      'Pets, animal travel and destination import requirements',
      'Shipping, storage, mail forwarding and first-30-days essentials',
      'Family, schools, dependants and emergency contacts',
      'Estate, wills, beneficiaries, guardianship and cross-border asset prompts',
    ],
    livingPriceGbp: 499,
    checkFields: [
      'email',
      'name',
      'originCountry',
      'destinationCountry',
      'destinationCity',
      'citizenships',
      'moveDate',
      'moveDateFlexibility',
      'moveReason',
      'householdType',
      'employmentStatus',
      'expectedUkDaysAfterMove',
      'hasUkProperty',
      'hasUkPensionIsaInvestments',
      'hasChildren',
      'hasPets',
      'destinationVisaStatus',
      'housingStatus',
      'bankingStatus',
      'topConcerns',
      'biggestWorry',
    ],
    livingReportFields: [
      'taxResidenceLastFiveYears',
      'expectedUkDaysCurrentTaxYear',
      'expectedUkDaysNextTaxYear',
      'ukTiesHomeWorkFamily',
      'ukWorkdaysAfterMove',
      'ukEmploymentOrBusinessAfterMove',
      'selfAssessmentStatus',
      'p85Status',
      'sa109Status',
      'studentLoanStatus',
      'nationalInsuranceContributionPlans',
      'ukPropertyDetails',
      'ukPropertySaleOrRentalPlans',
      'mortgageConsentStatus',
      'nonResidentLandlordSchemeStatus',
      'ukRentalAgentStatus',
      'isaDetails',
      'sippWorkplacePensionDetails',
      'statePensionNiRecordStatus',
      'investmentAccountsBrokerRestrictions',
      'companyEquityOrCrypto',
      'ukBankingContinuityPlan',
      'ukPhoneNumber2faPlan',
      'mailForwardingPlan',
      'destinationVisaRoute',
      'destinationResidenceStatus',
      'destinationBankingStatus',
      'destinationHealthcareStatus',
      'destinationHousingStatus',
      'documentsNeedingApostilleTranslationAttestation',
      'drivingLicenceCountry',
      'noClaimsInsuranceRecords',
      'dependants',
      'childrenAges',
      'schoolOrNurseryNeeds',
      'petsDetails',
      'petVaccinationMicrochipStatus',
      'shippingStorageNeeds',
      'temporaryAccommodationNeeds',
      'estateWillsGuardianshipStatus',
      'returnToUkIntentions',
      'expertAdvisersAlreadyEngaged',
    ],
    reportSections: [
      'executive_brief',
      'move_profile',
      'hidden_dependencies',
      'risk_map',
      'timeline',
      'uk_departure_admin',
      'tax_residence',
      'hmrc_self_assessment_p85',
      'banking_money',
      'property_pension_investments',
      'destination_setup',
      'documents_credentials_attestation',
      'credentials_licences_conversion',
      'pets_animal_travel',
      'shipping_storage_possessions',
      'family_school_dependants',
      'healthcare_insurance',
      'estate_wills_guardianship',
      'day_one_arrival',
      'first_90_days',
      'recommended_packages',
      'expert_questions',
      'change_log',
    ],
    packages: [
      'day_one_arrival_pack',
      'tax_residence_packet',
      'uk_departure_admin_pack',
      'banking_continuity',
      'property_pension_investments_packet',
      'documents_attestation_pack',
      'credentials_licences_conversion',
      'pet_relocation_readiness',
      'storage_shipping_plan',
      'estate_wills_packet',
      'first_90_days_concierge',
    ],
  },
] as const satisfies ReadonlyArray<Omit<RouteConfig, 'riskScoring'>>;

export const ROUTE_CONFIGS: RouteConfig[] = ROUTE_CONFIG_BASE.map((route) => ({
  ...route,
  riskScoring: riskScoringForRoute(route.routeKey, [...route.checkFields], [...route.livingReportFields]),
}));

export function getRouteBySlug(slug: string): RouteConfig | undefined {
  return ROUTE_CONFIGS.find((r) => r.slug === slug);
}

export function getRouteByKey(routeKey: string): RouteConfig | undefined {
  return ROUTE_CONFIGS.find((r) => r.routeKey === routeKey);
}

export function slugToRouteKey(slug: string): RouteKey | undefined {
  return getRouteBySlug(slug)?.routeKey;
}
