const SECTION_TITLES: Record<string, string> = {
  executive_brief: 'Executive Brief',
  move_profile: 'Move Profile',
  hidden_dependencies: 'Hidden Dependencies',
  risk_map: 'Risk Map',
  timeline: 'Timeline',
  uk_departure_admin: 'UK Departure Admin',
  tax_residence: 'Tax & Residence',
  hmrc_self_assessment_p85: 'HMRC, Self Assessment & P85',
  uae_residency_emirates_id: 'UAE Residency, Medical & Emirates ID',
  visa_admin_evisa_share_codes: 'eVisa, UKVI Account & Share Codes',
  student_visa_cas_evisa: 'CAS, Student Visa & eVisa',
  work_payroll_ni_tax_code: 'Work, Payroll, NI & Tax Code',
  banking_money: 'Banking & Money',
  banking_money_parent_funding: 'Banking, Money & Parent Funding',
  housing_ejari_utilities: 'Housing, Ejari & Utilities',
  housing_right_to_rent_utilities: 'Housing, Right to Rent & Utilities',
  accommodation_housing: 'Accommodation & Housing',
  healthcare_insurance: 'Healthcare & Insurance',
  healthcare_gp_nhs_insurance: 'Healthcare, GP & NHS',
  healthcare_gp_wellbeing: 'Healthcare, GP & Wellbeing',
  family_school_dependants: 'Family, School & Dependants',
  family_school_nursery_dependants: 'Family, School & Nursery',
  family_parent_communication: 'Family & Parent Communication',
  pets_animal_travel: 'Pets & Animal Travel',
  credentials_licences_attestation: 'Credentials, Licences & Attestation',
  credentials_licences_conversion: 'Credentials & Licences Conversion',
  documents_credentials: 'Documents & Credentials',
  documents_family_records: 'Family Records & Documents',
  documents_credentials_attestation: 'Documents, Credentials & Attestation',
  shipping_storage_possessions: 'Shipping, Storage & Possessions',
  property_pension_investments: 'Property, Pension & Investments',
  estate_wills_guardianship: 'Estate, Wills & Guardianship',
  destination_setup: 'Destination Setup',
  university_registration: 'University Registration',
  student_safety_scams: 'Safety & Scams',
  phone_transport_arrival_basics: 'Phone, Transport & Arrival Basics',
  first_90_days: 'First 90 Days',
  first_week_first_term: 'First Week & First Term',
  recommended_packages: 'Recommended Packages',
  expert_questions: 'Expert Questions',
  change_log: 'Change Log',
};

export function sectionTitle(key: string): string {
  return SECTION_TITLES[key] ?? key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}
