import type { RouteKey } from '@/lib/routes';

/** Realistic stub intake answers for UI/debug previews — no forms required. */
export const DEBUG_ANSWERS: Record<RouteKey, Record<string, string>> = {
  uk_to_dubai: {
    email: 'alex.morgan@example.com',
    name: 'Alex Morgan',
    originCountry: 'United Kingdom',
    destinationCountry: 'United Arab Emirates',
    destinationCity: 'Dubai',
    citizenships: 'British',
    moveDate: '2026-09-15',
    moveDateFlexibility: 'no',
    moveReason: 'Work transfer',
    householdType: 'family',
    hasChildren: 'yes',
    hasPets: 'no',
    employmentStatus: 'employed',
    visaStatus: 'not_started',
    housingStatus: 'not_started',
    bankingStatus: 'not_started',
    ownsUkProperty: 'yes',
    hasUkPensionIsaInvestments: 'yes',
    topConcerns: 'UK tax exit, UAE visa timing, Dubai banking, schools',
    biggestWorry: 'Getting banking and Ejari sorted before family arrives',
    currentUkTaxResidenceStatus: 'not_started',
    uaeVisaRoute: 'Employment residence visa',
    emiratesIdStatus: 'not_started',
    ejariStatus: 'not_started',
    healthInsuranceStatusUae: 'not_started',
    dependants: 'Spouse + 2 children',
    childrenAges: '4, 7',
    schoolOrNurseryNeeds: 'Year 1 and Year 3 — British curriculum preferred',
    documentsNeedingAttestation: 'Degree, marriage certificate, birth certificates',
  },
  professionals_to_uk: {
    email: 'sam.okafor@example.com',
    name: 'Sam Okafor',
    originCountry: 'Nigeria',
    destinationCountry: 'United Kingdom',
    destinationCity: 'London',
    citizenships: 'Nigerian',
    moveDate: '2026-08-01',
    workStartDate: '2026-08-15',
    householdType: 'partner',
    hasChildren: 'no',
    hasPets: 'no',
    employmentStatus: 'employed',
    visaStatus: 'in_progress',
    employerSupportLevel: 'partial',
    housingStatus: 'not_started',
    bankingStatus: 'not_started',
    previousUkResidence: 'no',
    topConcerns: 'eVisa, banking, right to rent, NI number',
    biggestWorry: 'Opening a UK bank account before payroll starts',
    evisaStatus: 'not_started',
    rightToWorkReadiness: 'not_started',
    nationalInsuranceNumberStatus: 'not_started',
  },
  students_to_uk: {
    email: 'mia.chen@example.com',
    name: 'Mia Chen',
    originCountry: 'Singapore',
    destinationCountry: 'United Kingdom',
    destinationCity: 'Manchester',
    studentAge: '19',
    university: 'University of Manchester',
    courseLevel: 'undergraduate',
    courseStartDate: '2026-09-22',
    householdType: 'student',
    hasChildren: 'no',
    hasPets: 'no',
    casStatus: 'sorted',
    visaStatus: 'in_progress',
    housingStatus: 'not_started',
    bankingStatus: 'not_started',
    parentInvolved: 'yes',
    arrivingAlone: 'yes',
    topConcerns: 'Accommodation, student bank account, arrival week',
    biggestWorry: 'Securing halls or private rent before CAS travel window',
    studentVisaApplicationStatus: 'in_progress',
    tuitionPaymentStatus: 'in_progress',
  },
  families_to_uk: {
    email: 'james.walsh@example.com',
    name: 'James Walsh',
    originCountry: 'Ireland',
    destinationCountry: 'United Kingdom',
    destinationCity: 'Bristol',
    moveDate: '2026-07-01',
    householdType: 'family',
    hasChildren: 'yes',
    hasPets: 'yes',
    partnerMoving: 'yes',
    childrenAges: '2, 5',
    visaStatus: 'not_started',
    primaryApplicantVisaStatus: 'in_progress',
    housingStatus: 'uncertain',
    bankingStatus: 'not_started',
    schoolNeeds: 'Reception and Year 1 places',
    topConcerns: 'Schools, spouse visa, housing chain',
    biggestWorry: 'School admissions timing vs tenancy start date',
    dependantVisaStatus: 'not_started',
    schoolOrNurseryNeeds: 'Nursery for 2yo, primary for 5yo',
  },
  leaving_uk: {
    email: 'priya.sharma@example.com',
    name: 'Priya Sharma',
    originCountry: 'United Kingdom',
    destinationCountry: 'Spain',
    destinationCity: 'Barcelona',
    moveDate: '2026-10-01',
    householdType: 'alone',
    hasChildren: 'no',
    hasPets: 'no',
    visaStatus: 'not_started',
    housingStatus: 'not_started',
    bankingStatus: 'not_started',
    ownsUkProperty: 'yes',
    hasUkPensionIsaInvestments: 'yes',
    topConcerns: 'UK tax exit, Spanish residence, UK property',
    biggestWorry: 'UK non-resident tax position and letting UK flat',
    destinationVisaStatus: 'not_started',
    p85Status: 'not_started',
    selfAssessmentStatus: 'in_progress',
  },
};
